export const RETRY_ERROR = 'Đã có lỗi xảy ra, vui lòng thử lại sau ít phút'
export const INTERNAL_ERROR = 'Lỗi hệ thống, vui lòng thử lại sau'
